const { chromium } = require(process.env.PLAYWRIGHT_MODULE || 'playwright');
const fs = require('node:fs');
const path = require('node:path');
const base = process.env.BASE_URL || 'http://127.0.0.1:3000';
const output = process.env.BROWSER_ARTIFACT_DIR || '/private/tmp/umbrella-browser-artifacts';
fs.mkdirSync(output, { recursive: true });
(async () => {
  const browser = await chromium.launch({ headless: true });
  const page = await browser.newPage({ viewport: { width: 1280, height: 900 } });
  const errors=[]; page.on('pageerror', error => errors.push(error.message));
  await page.goto(base);
  await page.waitForSelector('#intro', { state: 'hidden' });
  await page.waitForFunction(() => document.querySelectorAll('.chat-item').length === 8);
  await page.waitForTimeout(5500);
  await page.screenshot({ path: path.join(output, 'desktop.png') });
  await page.locator('#input').fill('Групповой черновик');
  await page.reload(); await page.waitForTimeout(1500);
  if (await page.locator('#input').inputValue() !== 'Групповой черновик') throw Error('group draft lost');
  await page.getByRole('button', { name: /^Five/ }).click();
  await page.locator('#input').fill('Мой текст. Только я пишу за Алину.');
  await page.getByRole('button', { name: 'Отправить сообщение', exact: true }).click();
  await page.waitForFunction(() => !document.getElementById('send').disabled);
  await page.waitForTimeout(300);
  const player = await page.locator('.mine .message-text').allTextContents();
  if (JSON.stringify(player)!==JSON.stringify(['Мой текст. Только я пишу за Алину.'])) throw Error('player message mismatch');
  await page.reload();
  await page.waitForTimeout(1500);
  await page.getByRole('button', { name: /^Five/ }).click();
  if (await page.locator('.mine').count() !== 1) throw Error('reload lost user history');
  const mobile = await browser.newPage({ viewport: { width: 390, height: 844 }, isMobile: true, hasTouch: true, deviceScaleFactor: 3 });
  mobile.on('pageerror', error => errors.push(error.message));
  await mobile.goto(base); await mobile.waitForTimeout(8000);
  await mobile.screenshot({ path: path.join(output, 'mobile-list.png') });
  await mobile.getByRole('button', { name: /^Five/ }).click();
  await mobile.screenshot({ path: path.join(output, 'mobile-chat.png') });
  const measure = await mobile.evaluate(() => ({ width: innerWidth, documentWidth: document.documentElement.scrollWidth, height: innerHeight, input: document.querySelector('#input').getBoundingClientRect().toJSON(), serviceWorker: !!navigator.serviceWorker.controller }));
  if (measure.documentWidth > measure.width) throw Error('horizontal overflow');
  await mobile.setViewportSize({ width: 390, height: 460 });
  await mobile.locator('#input').fill('Черновик при открытой клавиатуре');
  await mobile.screenshot({ path: path.join(output, 'mobile-keyboard.png') });
  const keyboard = await mobile.locator('#input').boundingBox();
  if (keyboard.y + keyboard.height > 460) throw Error('composer obscured');
  await mobile.reload(); await mobile.waitForTimeout(1500); await mobile.getByRole('button', { name: /^Five/ }).click();
  if (await mobile.locator('#input').inputValue() !== 'Черновик при открытой клавиатуре') throw Error('draft lost');
  await mobile.context().setOffline(true); await mobile.reload(); await mobile.waitForTimeout(500);
  if (await mobile.locator('.chat-item').count() !== 8) throw Error('offline shell unavailable');
  console.log(JSON.stringify({ player, measure, keyboard, errors, offlineShell: true, reload: true, draft: true }));
  await browser.close();
})().catch(e=>{ console.error(e);process.exit(1); });
